# Generated by Django 4.2 on 2024-08-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("password", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CS", "Consumer user"),
                            ("V", "Viewer user"),
                            ("P", "Premium user"),
                            ("N", "Normal user"),
                            ("DF", "Default user"),
                            ("DV", "Developer user"),
                            ("CT", "Creator user"),
                            ("MK", "Marker user"),
                            ("A", "Admin user"),
                            ("SP", "Super user"),
                            ("MG", "Manager user"),
                            ("SV", "Supervisor user"),
                            ("W", "Writer user"),
                            ("E", "Editor user"),
                        ],
                        default="N",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("username",),
            },
        ),
    ]
