name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.11-buster

    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass

    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.4.2

      - name: Install Dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          CORESETTINGS_DATABASES: '{"default": {"HOST": "db"}}'
          CORESETTINGS_LOCAL_SETTINGS_PATH: './core/core/settings/templates/settings.github.py'
